services:
  logic-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    stdin_open: true       # Чтобы можно было вводить выражения
    tty: true              # Поддержка терминала
    container_name: laba3
    restart: unless-stopped